version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: "rabbitmq"
    labels:
        NAME: "rabbitmq"
    command: rabbitmq-server
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
     - 15672
     - 5672

  authenticationapiservice:
    container_name: authentication-api
    image: ${DOCKER_REGISTRY-}authenticationapiservice
    build:
      context: .
      dockerfile: AuthenticationApiService\Dockerfile

  ocelotgateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: .
      dockerfile: OcelotGateway\Dockerfile
    ports:
        - 8001:80

  expensetracker.api:
    container_name: expenseTracker-api
    image: ${DOCKER_REGISTRY-}expensetrackerapi
    build:
      context: .
      dockerfile: ExpenseTracker.API/Dockerfile

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: # not actually needed, because the two services are on the same network.
      - "1433:1433" 
    environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "S3cur3P@ssW0rd!"


  fnsapi:
    container_name: fns-api
    image: ${DOCKER_REGISTRY-}fnsapi
    build:
      context: .
      dockerfile: FNSApi/Dockerfile

