version: '3.4'

services:
  authenticationapiservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  ocelotgateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

